default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  timeout: 5000

development:
  <<: *default
  database: twitter_development

test:
  <<: *default
  database: twitter_test

staging:
  <<: *default
  database: twitter_staging

production:
  <<: *default
  database: twitter_production
